sudo: required
dist: trusty
services:
- docker
env:
  global:
  - PKGFORGE_STATEFILE=/tmp/pkgforge
  - secure: Sq4cPX1tpL8FaSA6JITjvBrQbYPWjtuEobEmS5XceWt8pwAC6PSCcXw3TnsZetTQMZSr50OXZqtCrCKPI4+ECxh0wYl4j2ktbarpbouaJd89bKnZYB83rZDPIwtBBAh35bUMpJZ3LoDsbNRSZkNnQr63hHFgAdiU3tDy+UpXrgy2LbfZB9VwNtglfQnVyzUi5dVDO5D/RFHx8VQjAzpHa5fb7bcJIdSSXQtnqZVCcqdnomZekRDp2ULsjuzREh+um49ITM1rsVQ5P4YJoY5zjBaOSd9Lmjj9b/SAMkHG1ZS9rvNTHyn9lGKhN2qaB2AoNO55xsFiHuubCUbN1w4t0GR2s9PBN3uBYfn9kpqsL20h/Plb4YEWsprCN0CCsvyWw0B901z/gYt7xwvsKqKJPPgnwv5J94xXoKEw6d3zljIYh9SxjUbl90mEwzBsv03vOALDrFVmScyz+Id78wc7muMAcp3XPh7CqkMTlcLEyTHB6TOf7H4vj7PzCvGiTTe7KCWbx70AOlwXVYRObS90cnQ9KvJIDvUjedwv9lJINWyGSyCES2wUGjHdkXUoLYkwuyNVN9rEAN0rmzr3Ejv5kdbRgQpaiaMny8oN5kgXpd3g1BbiQRP1WKKLa+3g6bfj8k7VlgWLq51sNcwmFl/MUcg1z2qqLCc7GgQBT7wG9ew=
script: make
deploy:
  provider: script
  script: make release || travis_terminate 1
  skip_cleanup: true
  on:
    tags: true
notifications:
  email: false
  slack:
    secure: Jt8tMrf5eft5VJqFAPLuwh7r2eJvL2VOXTQddxsKkf+AqfrNHK6bPpc+kbiKFuJUo/WRPv7eTzlC0EmG6AkeaMoD6T/JHOlzoXLKx0fDhAD4G0ut5b6XgOKQxmYmZJqS1ZINrvga0WpwO0Y4ffDsW0jIEG/HOkELqhZdhKOtRHFmo0zks3MkAts+ejohp+AcJvMlOF4zSFV+iOisx22EGQSkrpp8ZLGaI+Dxzkzv/nFt5Tvjo+6NAE8iNUec99GIbtMQ0/UrSCtq9xR5Vm7Rt3QW6Y3FNk2LSOHS2SFqI7Cdw5+jWtZsZ5YDZYs0+ykkKUvNsZhUhGk9ILU2H+OXgxOGiUUcaRPOXvVz23uF7nx5dEsi6Lx4V9v0hPw+jw1l1FqxGaK/UHQ0jxwdFXqMMqbok7MUcQYHY5ygDEgprkW+lp0M0SDHsOjCmbBxC7oMAkB5iuPUwW8QiFLItL4LIuGRegYoWuXJVvhjs15K/5G3HuWvYeO3f4TA3r1lQqf8PqRzCfL2u8r7b2eANKx5SzF5MOoMguE7oTKEMrmf5OKSByMR1Ow7jWxyC8+h3kQchypxhb+sBukz77po4zXFcn6NuuVI7J0gwJOxtUYe0jgJJLAd8DZ0eWOabiI8szlbTKXf1TDiGyz8GZLcI4M9yiLYyUZZQRUI/6RDSjYM10s=
